[tool.poetry]
name = "autoreport"
version = "0.1.0"
description = "gerador de relatórios em LaTeX"
authors = ["Luís Felipe de Abreu Marciano"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
